#!/bin/bash

##########################################
Date : 04 feb 2024
About : listing the git version from scm using wget command
Author : Kishore
##########################################


which wget 1>/dev/null 2>/dev/null
if [ $? -ne 0 ]
then
        echo "please install wget and retry"
        exit 1
else
        echo "wget is already install"
fi
if [ -e "index.html" ]
then
        rm -rf index.html
        echo "removing index.html file"
fi

url=https://mirrors.edge.kernel.org/pub/software/scm/git/

wget $url

if [ $? -ne 0 ]
then
     echo "unable to download got from net"
     exit 2
fi

declare -a git_vers
echo "**************************please wait collecting git versions from scm***************************"
while read line
do
        git_vers+=($(echo $line | sed -n '/git-\([0-9]\+\.\)\+tar.gz/p' | awk -F '"' '{ print $2 }' | cut -c 5- | awk -F '.tar.gz' '{ print $1 }'))


done < index.html


echo "all the available git versions are: "
cnt=0
no_vers=${#git_vers[*]}
WIDTH=20
for each_ver in echo ${git_vers[*]}
do
     #echo -e "\t\t ${git_vers[$cnt]} \\t ${git_vers[$(($cnt+1))]} \\t ${git_vers[$(($cnt+2))]}"
     printf "%-*s %-*s %-*s %-*s %-*s\n" $WIDTH ${git_vers[$cnt]} $WIDTH ${git_vers[$(($cnt+1))]} $WIDTH ${git_vers[$(($cnt+2))]} $WIDTH ${git_vers[$(($cnt+3))]} $WIDTH ${git_vers[$(($cnt+4))]} $WIDTH ${git_vers[$(($cnt+5))]}
     cnt=$((cnt+3))
     if [ $cnt -ge $no_vers ]
     then
             break
     fi
done
